apiVersion: v2
name: gateway-helm
description: An http Helm chart for envoy
type: application
version: 0.0.8
appVersion: "1.0.0"
dependencies: []


# export CR_VERSION="v1.7.0"  # replace with the version you saw
# curl -LO "https://github.com/helm/chart-releaser/releases/download/${CR_VERSION}/chart-releaser_${CR_VERSION#v}_linux_amd64.tar.gz"
